[package]
name = "sepp"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.14"
tonic-prost = "0.14"
tokio = { version = "1", features = ["full"] }
prost = "0.14"
prost-types = "0.14"
prost-reflect = "0.16"
prost-protovalidate = "0.3"
uuid = { version = "1.23.1", features = ["v4"] }
fjall = "3"
flume = "0.11"
serde = { version = "1", features = ["derive"] }
figment = { version = "0.10", features = ["toml", "env"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
opentelemetry = { version = "0.31", default-features = false, features = ["trace"] }
opentelemetry_sdk = { version = "0.31", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { version = "0.31", default-features = false, features = ["grpc-tonic", "trace"] }
tracing-opentelemetry = "0.32.1"
opentelemetry-semantic-conventions = "0.31"


[build-dependencies]
tonic-prost-build = "0.14"
prost-build = "0.14"
prost-reflect-build = "0.16"
protoc-bin-vendored = "3"
