[package]
name = "sepp"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { version = "0.14", features = ["tls-ring"] }
tonic-prost = "0.14"
tokio = { version = "1", features = ["full"] }
prost = "0.14"
prost-types = "0.14"
prost-reflect = "0.16.4"
prost-protovalidate = "0.4"
uuid = { version = "1.23.1", features = ["v4"] }
fjall = "3"
flume = "0.12"
serde = { version = "1", features = ["derive"] }
figment = { version = "0.10", features = ["toml", "env"] }
arc-swap = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
opentelemetry = { version = "0.32", default-features = false, features = ["trace", "metrics"] }
opentelemetry_sdk = { version = "0.32", default-features = false, features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.32", default-features = false, features = ["grpc-tonic", "trace", "metrics"] }
tracing-opentelemetry = "0.33"
opentelemetry-semantic-conventions = "0.32"


[build-dependencies]
tonic-prost-build = "0.14"
prost-build = "0.14"
prost-reflect-build = "0.16"

[dev-dependencies]
rcgen = "0.14"

[profile.release]
lto = "fat"
codegen-units = 1